resolver 127.0.0.11 valid=10s;

server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # 정적 파일 서빙
    location / {
        try_files $uri $uri/ =404;
    }

    # 물류 대시보드 API 프록시
    location /logistics/api/ {
        rewrite ^/logistics/api/(.*)$ /api/$1 break;
        proxy_pass http://becorelab-logistics:8082;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
